export const GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";

export const GET_POST_LOADING = "GET_POST_LOADING";
export const GET_POST_ERROR = "GET_POST_ERROR";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const GET_DETAIL_LOADING = "GET_DETAIL_LOADING";
export const GET_DETAIL_ERROR = "GET_DETAIL_ERROR";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";

export const GET_AUTH_LOADING = "GET_AUTH_LOADING";
export const GET_AUTH_ERROR = "GET_AUTH_ERROR";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
